# Generated by Django 5.0 on 2023-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_matricol', models.PositiveIntegerField()),
                ('prenume', models.CharField(max_length=50)),
                ('nume', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('specializarea', models.CharField(max_length=50)),
                ('media', models.FloatField()),
            ],
        ),
    ]
